
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "foot"
local fileManager = "nautilus"
local browser     = "google-chrome"
local menu        = "hyprlauncher"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

hl.on("hyprland.start", function()
  hl.exec_cmd("uwsm-app -- waybar || waybar")
  hl.exec_cmd("uwsm-app -- hyprpaper || hyprpaper")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
-- hyprlauncher wraps Terminal=true .desktop files (vim, btop) with $TERMINAL.
hl.env("TERMINAL", "foot")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper  = 0,     -- disable the default mascot wallpapers
        disable_hyprland_logo    = true,  -- solid background_color instead of the logo/anime wallpaper
        disable_splash_rendering = true,  -- no "go to settings to activate" splash text
        background_color         = "0x111111",
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

local function bind(keys, dispatcher, description, extra)
    extra = extra or {}
    extra.description = description
    return hl.bind(keys, dispatcher, extra)
end

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal), "Terminal")
bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal), "Terminal")
bind(mainMod .. " + SHIFT + RETURN", hl.dsp.exec_cmd(browser), "Browser")
bind(mainMod .. " + W", hl.dsp.window.close(), "Close window")
bind(mainMod .. " + CTRL + L", hl.dsp.exec_cmd("hyprlock"), "Lock")
bind(mainMod .. " + K", hl.dsp.exec_cmd("hypr-show-keybinds || sh " .. os.getenv("HOME") .. "/nixos-config/hypr/show-keybinds.sh"), "Show keybindings")
bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"), "Exit Hyprland")
bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager), "File manager")
bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu), "Launcher")
bind(mainMod .. " + SHIFT + SPACE", hl.dsp.exec_cmd("pkill waybar || waybar"), "Toggle bar")
bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd(browser), "Browser")
bind(mainMod .. " + SHIFT + ALT + B", hl.dsp.exec_cmd(browser .. " --incognito"), "Browser (private)")
bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd(fileManager), "File manager")
bind(mainMod .. " + ALT + SHIFT + F", hl.dsp.exec_cmd(fileManager .. " --new-window"), "File manager (new window)")

-- Universal copy/paste/cut (Omarchy). CTRL/SHIFT+Insert works in terminals and GUI apps.
-- send_shortcut can leave synthetic keys stuck; send down/up ourselves.
-- https://github.com/hyprwm/Hyprland/discussions/14099
local function send_shortcut_once(mods, key)
    return function()
        hl.dispatch(hl.dsp.send_key_state({ mods = mods, key = key, state = "down", window = "activewindow" }))
        hl.timer(function()
            hl.dispatch(hl.dsp.send_key_state({ mods = mods, key = key, state = "up", window = "activewindow" }))
        end, { timeout = 50, type = "oneshot" })
    end
end

bind(mainMod .. " + C", send_shortcut_once("CTRL", "Insert"), "Copy")
bind(mainMod .. " + V", send_shortcut_once("SHIFT", "Insert"), "Paste")
bind(mainMod .. " + X", send_shortcut_once("CTRL", "X"), "Cut")

-- Window tiling / positioning (Omarchy tiling-v2)
bind(mainMod .. " + J", hl.dsp.layout("togglesplit"), "Toggle split")
bind(mainMod .. " + P", hl.dsp.window.pseudo(), "Pseudo window")
bind(mainMod .. " + T", hl.dsp.window.float({ action = "toggle" }), "Toggle floating")
bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }), "Fullscreen")
bind(mainMod .. " + CTRL + F", hl.dsp.window.fullscreen_state({ internal = 0, client = 2 }), "Tiled fullscreen")
bind(mainMod .. " + ALT + F", hl.dsp.window.fullscreen({ mode = "maximized" }), "Maximize")
bind(mainMod .. " + O", function()
    hl.dispatch(hl.dsp.window.float({ action = "toggle" }))
    hl.dispatch(hl.dsp.window.pin({ action = "toggle" }))
end, "Pop window out (float and pin)")
bind(mainMod .. " + L", function()
    local layout = hl.get_config("general.layout")
    if layout == "master" then
        hl.config({ general = { layout = "dwindle" } })
    else
        hl.config({ general = { layout = "master" } })
    end
end, "Toggle workspace layout")

bind(mainMod .. " + left",  hl.dsp.focus({ direction = "l" }), "Focus left")
bind(mainMod .. " + right", hl.dsp.focus({ direction = "r" }), "Focus right")
bind(mainMod .. " + up",    hl.dsp.focus({ direction = "u" }), "Focus up")
bind(mainMod .. " + down",  hl.dsp.focus({ direction = "d" }), "Focus down")

-- Switch / move windows with SUPER + [1-9; 0] on the physical number row
-- (Omarchy-style keycodes so SHIFT+number still hits 1-0, not !@#).
for i = 1, 10 do
    local code = "code:" .. (9 + i) -- 1 → code:10 … 0 → code:19
    bind(mainMod .. " + " .. code,                  hl.dsp.focus({ workspace = i }), "Switch to workspace " .. i)
    bind(mainMod .. " + SHIFT + " .. code,          hl.dsp.window.move({ workspace = i, follow = true }), "Move window to workspace " .. i)
    bind(mainMod .. " + SHIFT + ALT + " .. code,    hl.dsp.window.move({ workspace = i, follow = false }), "Move window silently to workspace " .. i)
end

bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"), "Toggle scratchpad")
bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }), "Move window to scratchpad")
bind(mainMod .. " + ALT + S",   hl.dsp.window.move({ workspace = "special:magic", follow = false }), "Move window to scratchpad silently")

bind(mainMod .. " + TAB",         hl.dsp.focus({ workspace = "e+1" }), "Next workspace")
bind(mainMod .. " + SHIFT + TAB", hl.dsp.focus({ workspace = "e-1" }), "Previous workspace")
bind(mainMod .. " + CTRL + TAB",  hl.dsp.focus({ workspace = "previous" }), "Former workspace")

bind(mainMod .. " + SHIFT + ALT + left",  hl.dsp.workspace.move({ monitor = "l" }), "Move workspace to left monitor")
bind(mainMod .. " + SHIFT + ALT + right", hl.dsp.workspace.move({ monitor = "r" }), "Move workspace to right monitor")
bind(mainMod .. " + SHIFT + ALT + up",    hl.dsp.workspace.move({ monitor = "u" }), "Move workspace to up monitor")
bind(mainMod .. " + SHIFT + ALT + down",  hl.dsp.workspace.move({ monitor = "d" }), "Move workspace to down monitor")

bind(mainMod .. " + SHIFT + left",  hl.dsp.window.swap({ direction = "l" }), "Swap window left")
bind(mainMod .. " + SHIFT + right", hl.dsp.window.swap({ direction = "r" }), "Swap window right")
bind(mainMod .. " + SHIFT + up",    hl.dsp.window.swap({ direction = "u" }), "Swap window up")
bind(mainMod .. " + SHIFT + down",  hl.dsp.window.swap({ direction = "d" }), "Swap window down")

bind("ALT + TAB", function()
    hl.dispatch(hl.dsp.window.cycle_next())
    hl.dispatch(hl.dsp.window.bring_to_top())
end, "Next window")
bind("ALT + SHIFT + TAB", function()
    hl.dispatch(hl.dsp.window.cycle_next({ next = false }))
    hl.dispatch(hl.dsp.window.bring_to_top())
end, "Previous window")

bind("CTRL + ALT + TAB",         hl.dsp.focus({ monitor = "+1" }), "Next monitor")
bind("CTRL + ALT + SHIFT + TAB", hl.dsp.focus({ monitor = "-1" }), "Previous monitor")

-- Resize: code:20 = minus, code:21 = equal
bind(mainMod .. " + code:20",               hl.dsp.window.resize({ x = -100, y = 0, relative = true }), "Expand window left")
bind(mainMod .. " + code:21",               hl.dsp.window.resize({ x = 100,  y = 0, relative = true }), "Shrink window left")
bind(mainMod .. " + SHIFT + code:20",       hl.dsp.window.resize({ x = 0, y = -100, relative = true }), "Shrink window up")
bind(mainMod .. " + SHIFT + code:21",       hl.dsp.window.resize({ x = 0, y = 100,  relative = true }), "Expand window down")
bind(mainMod .. " + ALT + code:20",         hl.dsp.window.resize({ x = -25, y = 0, relative = true }), "Expand window left a little")
bind(mainMod .. " + ALT + code:21",         hl.dsp.window.resize({ x = 25,  y = 0, relative = true }), "Shrink window left a little")
bind(mainMod .. " + SHIFT + ALT + code:20", hl.dsp.window.resize({ x = 0, y = -25, relative = true }), "Shrink window up a little")
bind(mainMod .. " + SHIFT + ALT + code:21", hl.dsp.window.resize({ x = 0, y = 25,  relative = true }), "Expand window down a little")
bind(mainMod .. " + CTRL + code:20",        hl.dsp.window.resize({ x = -300, y = 0, relative = true }), "Expand window left a lot")
bind(mainMod .. " + CTRL + code:21",        hl.dsp.window.resize({ x = 300,  y = 0, relative = true }), "Shrink window left a lot")
bind(mainMod .. " + CTRL + SHIFT + code:20",hl.dsp.window.resize({ x = 0, y = -300, relative = true }), "Shrink window up a lot")
bind(mainMod .. " + CTRL + SHIFT + code:21",hl.dsp.window.resize({ x = 0, y = 300,  relative = true }), "Expand window down a lot")

bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), "Scroll workspace forward")
bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }), "Scroll workspace backward")
bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   "Move window", { mouse = true })
bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), "Resize window", { mouse = true })

bind(mainMod .. " + G",         hl.dsp.group.toggle(), "Toggle window grouping")
bind(mainMod .. " + ALT + G",   hl.dsp.window.move({ out_of_group = true }), "Move window out of group")
bind(mainMod .. " + ALT + left",  hl.dsp.window.move({ into_group = "l" }), "Move window to group on left")
bind(mainMod .. " + ALT + right", hl.dsp.window.move({ into_group = "r" }), "Move window to group on right")
bind(mainMod .. " + ALT + up",    hl.dsp.window.move({ into_group = "u" }), "Move window to group on top")
bind(mainMod .. " + ALT + down",  hl.dsp.window.move({ into_group = "d" }), "Move window to group on bottom")
bind(mainMod .. " + ALT + TAB",         hl.dsp.group.next(), "Next window in group")
bind(mainMod .. " + ALT + SHIFT + TAB", hl.dsp.group.prev(), "Previous window in group")
bind(mainMod .. " + CTRL + left",  hl.dsp.group.prev(), "Previous window in group")
bind(mainMod .. " + CTRL + right", hl.dsp.group.next(), "Next window in group")
bind(mainMod .. " + ALT + mouse_down", hl.dsp.group.next(), "Next window in group")
bind(mainMod .. " + ALT + mouse_up",   hl.dsp.group.prev(), "Previous window in group")
for index = 1, 5 do
    bind(mainMod .. " + ALT + code:" .. (index + 9), hl.dsp.group.active({ index = index }), "Switch to group window " .. index)
end

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
